### ISSUE TITLE
README: Documentation github to update for correct install link

### ISSUE THREAD

**Issue by zigomatichub** [mr-manuel/venus-os_dbus-enphase-envoy#10]
Hello Manuel,
Thank you for the github.
I found one small issue with the wget in installation process.
github /mr-manuel/venus-os_dbus-_**mqtt**_-enphase-envoy -> should be --> https://github.com/mr-manuel/venus-os_dbus-enphase-envoy

and below lines also contain mqtt

Have a good day,
Zigomatic

**Comment by mr-manuel** [comment]
Thanks, I corrected it.
