### ISSUE TITLE
Firmware D8 does not get token

### ISSUE THREAD

**Issue by broekieman** [mr-manuel/venus-os_dbus-enphase-envoy#13]
I have firmware D8 en if i use D7 there is first a problem with login to get the token.
When i try accessing [http](http://xxx.xxx.xxx.xxx/production.json?details=1)

Logfile:
fetch_production_historic(): HTTP request took longer than 5 seconds:
WARNING:root:--> data_production_historic not yet ready after 60 seconds.
2024-10-15 09:36:31.153306500 Try accessing http://192.168.178.90/production.json?details=1 from your PC and see,
2024-10-15 09:36:31.153310500 if it downloads a file with JSON content
When i click on the link i get: 
<img width="722" alt="image" src="https://github.com/user-attachments/assets/e6d0840e-70bf-42a2-bcb5-e250391de792">

When i login manually and click again to download JSON content, i get:
{"production":[{"type":"inverters","activeCount":12,"readingTime":1728985168,"wNow":2488,"whLifetime":9170289}],"storage":[{"type":"acb","activeCount":0,"readingTime":0,"wNow":0,"whNow":0,"state":"idle"}]}

So the ploblem seems to be the login for getting the token and HTTP request took longer than 5 seconds

**Comment by mr-manuel** [comment]
This was already solved.
