### ISSUE TITLE
Showing incorrect values

### ISSUE THREAD

**Issue by tfranssen** [mr-manuel/venus-os_dbus-enphase-envoy#2]
The Envoy Stream is throwing incorrect values. It differs from http://envoy/production.json. Do others also see this problem?

**Comment by mr-manuel** [comment]
How much does it differ? Can you see this also after a reboot or only if it's running for a while? I'm tracking both values writing them into an InfluxDB.

Can you post a screenshot of your Venus OS and  http://envoy/home opened side by side?

**Comment by tfranssen** [comment]
I think issue is that `/stream/meter` only works if you have an external meter connected which I don't have. I think I will fork your project and adjust it to read the `production.json?details=1` data which seems to be correct. 

<img width="977" alt="image" src="https://user-images.githubusercontent.com/54217714/203775727-f8b2ffec-110e-4880-9bcb-0fafb0241e83.png">

**Comment by tfranssen** [comment]
This is an example of stream/meters: 
`{
  "production": {
    "ph-a": {
      "p": 0,
      "q": 0,
      "s": 0,
      "v": 230.855,
      "i": 0,
      "pf": -1,
      "f": 50
    },
    "ph-b": {
      "p": 0,
      "q": 0,
      "s": 0,
      "v": 0,
      "i": 0,
      "pf": 0,
      "f": 0
    },
    "ph-c": {
      "p": 0,
      "q": 0,
      "s": 0,
      "v": 0,
      "i": 0,
      "pf": 0,
      "f": 0
    }
  },
  "net-consumption": {
    "ph-a": {
      "p": 0,
      "q": 0,
      "s": 0,
      "v": 230.736,
      "i": 0,
      "pf": 0,
      "f": 50
    },
    "ph-b": {
      "p": -0.03,
      "q": 0,
      "s": 0.068,
      "v": 7.981,
      "i": 0.012,
      "pf": -1,
      "f": 50
    },
    "ph-c": {
      "p": 0,
      "q": 0,
      "s": 0,
      "v": 6.867,
      "i": 0,
      "pf": 0,
      "f": 50
    }
  },
  "total-consumption": {
    "ph-a": {
      "p": 0,
      "q": 0,
      "s": 0,
      "v": 230.795,
      "i": 0,
      "pf": 0,
      "f": 50
    },
    "ph-b": {
      "p": -0.093,
      "q": 0,
      "s": 1.425,
      "v": 5.104,
      "i": 0.279,
      "pf": -0.07,
      "f": 50
    },
    "ph-c": {
      "p": -0.149,
      "q": 0,
      "s": 0.822,
      "v": 5.721,
      "i": 0.144,
      "pf": -0.18,
      "f": 50
    }
  }
}`

and this is an example of `http://envoy/production.json?details=1`

`{
  "production": [
    {
      "type": "inverters",
      "activeCount": 9,
      "readingTime": 1669290157,
      "wNow": 588,
      "whLifetime": 3379493
    },
    {
      "type": "eim",
      "activeCount": 0,
      "measurementType": "production",
      "readingTime": 1669290158,
      "wNow": 0,
      "whLifetime": 0,
      "varhLeadLifetime": 0,
      "varhLagLifetime": 0,
      "vahLifetime": 0,
      "rmsCurrent": 0,
      "rmsVoltage": 230.774,
      "reactPwr": 0,
      "apprntPwr": 0,
      "pwrFactor": 0,
      "whToday": 0,
      "whLastSevenDays": 0,
      "vahToday": 0,
      "varhLeadToday": 0,
      "varhLagToday": 0,
      "lines": [
        {
          "wNow": 0,
          "whLifetime": 0,
          "varhLeadLifetime": 0,
          "varhLagLifetime": 0,
          "vahLifetime": 0,
          "rmsCurrent": 0,
          "rmsVoltage": 230.774,
          "reactPwr": 0,
          "apprntPwr": 0,
          "pwrFactor": 0,
          "whToday": 0,
          "whLastSevenDays": 0,
          "vahToday": 0,
          "varhLeadToday": 0,
          "varhLagToday": 0
        }
      ]
    }
  ],
  "consumption": [
    {
      "type": "eim",
      "activeCount": 0,
      "measurementType": "total-consumption",
      "readingTime": 1669290158,
      "wNow": -0.037,
      "whLifetime": 0,
      "varhLeadLifetime": 0,
      "varhLagLifetime": 0,
      "vahLifetime": 0,
      "rmsCurrent": -0.011,
      "rmsVoltage": 238.143,
      "reactPwr": 0,
      "apprntPwr": -2.657,
      "pwrFactor": -1,
      "whToday": 0,
      "whLastSevenDays": 0,
      "vahToday": 0,
      "varhLeadToday": 0,
      "varhLagToday": 0,
      "lines": [
        {
          "wNow": 0,
          "whLifetime": 0,
          "varhLeadLifetime": 0,
          "varhLagLifetime": 0,
          "vahLifetime": 0,
          "rmsCurrent": 0,
          "rmsVoltage": 230.719,
          "reactPwr": 0,
          "apprntPwr": 0,
          "pwrFactor": 0,
          "whToday": 0,
          "whLastSevenDays": 0,
          "vahToday": 0,
          "varhLeadToday": 0,
          "varhLagToday": 0
        },
        {
          "wNow": -0.21,
          "whLifetime": 0,
          "varhLeadLifetime": 0,
          "varhLagLifetime": 0,
          "vahLifetime": 0,
          "rmsCurrent": 0.28,
          "rmsVoltage": 5.104,
          "reactPwr": 0,
          "apprntPwr": 1.431,
          "pwrFactor": -0.15,
          "whToday": 0,
          "whLastSevenDays": 0,
          "vahToday": 0,
          "varhLeadToday": 0,
          "varhLagToday": 0
        },
        {
          "wNow": -0.215,
          "whLifetime": 0,
          "varhLeadLifetime": 0,
          "varhLagLifetime": 0,
          "vahLifetime": 0,
          "rmsCurrent": 0.144,
          "rmsVoltage": 5.721,
          "reactPwr": 0,
          "apprntPwr": 0.822,
          "pwrFactor": -0.26,
          "whToday": 0,
          "whLastSevenDays": 0,
          "vahToday": 0,
          "varhLeadToday": 0,
          "varhLagToday": 0
        }
      ]
    },
    {
      "type": "eim",
      "activeCount": 0,
      "measurementType": "net-consumption",
      "readingTime": 1669290158,
      "wNow": -0.037,
      "whLifetime": 0,
      "varhLeadLifetime": 0,
      "varhLagLifetime": 0,
      "vahLifetime": 0,
      "rmsCurrent": 0.011,
      "rmsVoltage": 245.511,
      "reactPwr": 0,
      "apprntPwr": 0.06,
      "pwrFactor": 0,
      "whToday": 0,
      "whLastSevenDays": 0,
      "vahToday": 0,
      "varhLeadToday": 0,
      "varhLagToday": 0,
      "lines": [
        {
          "wNow": 0,
          "whLifetime": 0,
          "varhLeadLifetime": 0,
          "varhLagLifetime": 0,
          "vahLifetime": 0,
          "rmsCurrent": 0,
          "rmsVoltage": 230.663,
          "reactPwr": 0,
          "apprntPwr": 0,
          "pwrFactor": -1,
          "whToday": 0,
          "whLastSevenDays": 0,
          "vahToday": 0,
          "varhLeadToday": 0,
          "varhLagToday": 0
        },
        {
          "wNow": -0.037,
          "whLifetime": 0,
          "varhLeadLifetime": 0,
          "varhLagLifetime": 0,
          "vahLifetime": 0,
          "rmsCurrent": 0.011,
          "rmsVoltage": 7.981,
          "reactPwr": 0,
          "apprntPwr": 0.06,
          "pwrFactor": -1,
          "whToday": 0,
          "whLastSevenDays": 0,
          "vahToday": 0,
          "varhLeadToday": 0,
          "varhLagToday": 0
        },
        {
          "wNow": 0,
          "whLifetime": 0,
          "varhLeadLifetime": 0,
          "varhLagLifetime": 0,
          "vahLifetime": 0,
          "rmsCurrent": 0,
          "rmsVoltage": 6.867,
          "reactPwr": 0,
          "apprntPwr": 0,
          "pwrFactor": -1,
          "whToday": 0,
          "whLastSevenDays": 0,
          "vahToday": 0,
          "varhLeadToday": 0,
          "varhLagToday": 0
        }
      ]
    }
  ],
  "storage": [
    {
      "type": "acb",
      "activeCount": 0,
      "readingTime": 0,
      "wNow": 0,
      "whNow": 0,
      "state": "idle"
    }
  ]
}`

I think `http://envoy/api/v1/production/inverters` is also a good option, it looks like this gets more often refreshed. 

`[
  {
    "serialNumber": "122036002154",
    "lastReportDate": 1669290177,
    "devType": 1,
    "lastReportWatts": 154,
    "maxReportWatts": 154
  },
  {
    "serialNumber": "122037000277",
    "lastReportDate": 1669290185,
    "devType": 1,
    "lastReportWatts": 16,
    "maxReportWatts": 23
  },
  {
    "serialNumber": "122037000111",
    "lastReportDate": 1669290179,
    "devType": 1,
    "lastReportWatts": 14,
    "maxReportWatts": 19
  },
  {
    "serialNumber": "122037010814",
    "lastReportDate": 1669290188,
    "devType": 1,
    "lastReportWatts": 35,
    "maxReportWatts": 39
  },
  {
    "serialNumber": "122037000271",
    "lastReportDate": 1669290183,
    "devType": 1,
    "lastReportWatts": 16,
    "maxReportWatts": 84
  },
  {
    "serialNumber": "122037010990",
    "lastReportDate": 1669290190,
    "devType": 1,
    "lastReportWatts": 18,
    "maxReportWatts": 21
  },
  {
    "serialNumber": "122037000431",
    "lastReportDate": 1669290177,
    "devType": 1,
    "lastReportWatts": 153,
    "maxReportWatts": 157
  },
  {
    "serialNumber": "122037000029",
    "lastReportDate": 1669290183,
    "devType": 1,
    "lastReportWatts": 149,
    "maxReportWatts": 151
  },
  {
    "serialNumber": "122036055716",
    "lastReportDate": 1669290191,
    "devType": 1,
    "lastReportWatts": 41,
    "maxReportWatts": 44
  }
]
`

**Comment by mr-manuel** [comment]
Ok. Since the production.json is already fetched this is no issue. I add an option, so you can choose where you want to get your data from.

**Comment by tfranssen** [comment]
Ah that would be awesome! Great!

**Comment by mr-manuel** [comment]
Regarding the data from `http://envoy/api/v1/production/inverters` the data is not updated quite often. For testing I fetched the data every 15 seconds, but the value is updated from the Envoy only every 900 seconds.

![grafik](https://user-images.githubusercontent.com/12592765/203784154-09216921-1934-49e7-8f50-4ff0719bb948.png)

The data from `http://envoy/production.json?details=1` shows the data from the moment you fetch it.

**Comment by mr-manuel** [comment]
I checked again your data. The data from `/stream/meter` and `/production.json?details=1` is the same. Only in `/production.json?details=1` you have additionally a sum of all inverters, but you don't know how much on which phase. This would result in incorrect data. Is there a reason why you did not connect any CT? How many phases do your grid and PV have?

**Comment by tfranssen** [comment]
Are you sure you mean `/stream/meter` and `/production.json?details=1` and not `api/v1/production/inverters` and `/production.json?details=1`? In stream there should be a value for P in the first phase, right? Like the field below:
```
{
  "production": {
    "ph-a": {
      "p": 0,
```

I did not install the system myself, I am thinking about adding a sensor now. Would be nice to have more detailed information. Or I could use an unused phase on my ET340 smart meter.

**Comment by mr-manuel** [comment]
Yes I am sure :) the data from `/stream/meter` is contained in the data from `/production.json?details=1`, only the names are different.
`api/v1/production/inverters` contains completely other data.

The strange thing in your installation is that normally the Envoy is shipped with two CT's. When was your system installed and from which country are you?

**Comment by tfranssen** [comment]
Ah sorry now I get what you meant. You are right!

**Comment by mr-manuel** [comment]
Hi @tfranssen, have you any news?
