### ISSUE TITLE
No device

### ISSUE THREAD

**Issue by jeroenkl** [mr-manuel/venus-os_dbus-enphase-envoy#4]
Hi Mr-Manuel,

I'm running venus 2.93 and tried your application but I cannot get it to work.

- 2023-02-18 14:10:20.247941500 *** starting dbus-enphase-envoy ***
- /service/dbus-enphase-envoy: up (pid 1864) 12400 seconds
- When enabling MQTT I see perfect the enphase json info with MQTT explorer.
- I don't see any new device in venus GUI, no 'PV inverter', or 'enphase PV'

Anything I could check?

**Comment by mr-manuel** [comment]
Hi, try to change the position in the config.ini. I had the same problem with v3.00~15.

**Comment by jeroenkl** [comment]
Yes, I tried position 0, 1 and 2 same result:

; position (connected input/output) of the PV inverter
; 0 = AC input 1 (select this if you don't have a MultiPlus or Quattro)
; 1 = AC output
; 2 = AC input 2
position = 2

**Comment by jeroenkl** [comment]
Do I need to install additional dbus services?

**Comment by jeroenkl** [comment]
Just tested it also with beta v3.00~17, same issue

**Comment by mr-manuel** [comment]
1. Did you restart the driver after changing the position?
2. Do you see the inverter in the GUI -> Menu (Device List)?
3. What other devices do you have?
4. What are you seeing with `dbus-spy`?

No additional dbus services are required.

**Comment by jeroenkl** [comment]
Thanks!
1: Yes
2: No
3: see my dbus-spy output.
I've a node-red to MQTT PV-inverter which has Unit ID=1, I already removed it and didn't got the enphase inverter with other Unit ID


com.victronenergy.adc
com.victronenergy.battery.ttyUSB0                           SmartShunt 500A/50mV
com.victronenergy.battery.ttyUSB2                           SerialBattery(Jkbms)
com.victronenergy.ble
com.victronenergy.fronius
com.victronenergy.hub4
com.victronenergy.logger
com.victronenergy.modbusclient.tcp
com.victronenergy.modbustcp
com.victronenergy.platform
com.victronenergy.pvinverter.mqtt_cb002_SMA           Pvinverter sensor via MQTT
com.victronenergy.qwacs
com.victronenergy.settings
com.victronenergy.system
com.victronenergy.vebus.ttyUSB1                       MultiPlus-II 48/3000/35-32

**Comment by mr-manuel** [comment]
Can you increase the loglevel from `WARNING` to `DEBUG` and recheck the logfile?

https://github.com/mr-manuel/venus-os_dbus-enphase-envoy/blob/dc3aa33fb1c432d67950cd88b62a4056b6efc649/dbus-enphase-envoy/dbus-enphase-envoy.py#L25

**Comment by jeroenkl** [comment]
2023-02-18 19:40:01.070014500 INFO:root:--> data_meter_stream not yet ready
2023-02-18 19:40:01.393377500 DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.2.160:80
2023-02-18 19:40:01.458333500 DEBUG:urllib3.connectionpool:http://192.168.2.160:80 "GET /stream/meter HTTP/1.1" 401 0
2023-02-18 19:40:01.557049500 DEBUG:urllib3.connectionpool:http://192.168.2.160:80 "GET /stream/meter HTTP/1.1" 200 None
2023-02-18 19:40:02.071835500 INFO:root:--> data_meter_stream not yet ready
2023-02-18 19:40:02.541480500 DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.2.160:80

**Comment by mr-manuel** [comment]
It doesn't matter, if there is sun or not. Which Envoy-S firmware version do you have?

Can you successfully login to http://192.168.2.160/installer/setup/home#overview with the installer credentials? The error message in line 3 tells that you are not authorised to access the URL.

How have you generated the installer password?

**Comment by jeroenkl** [comment]
Yes I'm able to login with installer account. Password double checked in the config.ini file
earlier today I got a perfect Json data in MQTT when I enable MQTT in the config.ini

Software Version
D5.0.55 (4f2662)

**Comment by mr-manuel** [comment]
1. Can you access http://192.168.2.160/stream/meter from your PC?
2. Are the devices in the same 192.168.1.x network?
3. Have you already power cycled the Envoy?
4. Are you fetching data from the Envoy with other devices?
5. Can you post your config.ini without passwords?

The last option would be a remote TeamViewer session.

**Comment by jeroenkl** [comment]
1: Yes, but got a zero 0 als a return currently
2: Yes, they are all in subnet 192.168.2.x
3: No, just performed
4: Yes, but stopped it now
5: Yes:

`; CONFIG FILE
; GitHub reporitory: https://github.com/mr-manuel/venus-os_dbus-enphase-envoy
; remove semicolon ; to enable desired setting

[ENVOY]
; IP addess or FQDN of the Enphase Envoy
address = 192.168.2.160

; Requires the installer password
; can be generated with passwordCalc.py from this repository or https://github.com/sarnau/EnphaseEnergy
; you can test the credentials by opening http://IP_ADDR_OR_FQDN/installer/setup/home#overview
; with the username installer and the generated password
password = XXXXXX

; Time (seconds) between JSON requests
; default: 3600
; minimum: 900
fetch_production_historic_interval = 3600


[PV]
; Max rated power (in Watts) of the inverter
max = 295
; position (connected input/output) of the PV inverter
; 0 = AC input 1 (select this if you don't have a MultiPlus or Quattro)
; 1 = AC output
; 2 = AC input 2
position = 1
; how many inverters are connected?
inverter_count = 18
; specify inverter type, e.g. M215, IQ6, IQ7A, IQ8A
inverter_type = IQ7A


[DATA]
; Enables fetching of device status data (Microinverters, Q-Relays)
fetch_devices = 1
; Time (seconds) between requests for devices
; default: 3600
; minimum: 60
fetch_devices_interval = 3600
; How to publish data: 0 = publish only when data changed; 1 = publish everytime
; default: 0
fetch_devices_publishing_type = 0

; Enables fetching of Microinverters production data
fetch_inverters = 1
; Time (seconds) between requests for inverters
; default: 60
; minimum: 5
fetch_inverters_interval = 60
; How to publish data: 0 = publish only when data changed; 1 = publish everytime
; default: 0
fetch_inverters_publishing_type = 1

; Enable fetching of event data
fetch_events = 1
; Time (seconds) between requests for events
; default: 3600
; minimum: 900
fetch_events_interval = 3600
; How to publish data: 0 = publish only when data changed; 1 = publish everytime
; default: 0
fetch_events_publishing_type = 0


[MQTT]
; Enables MQTT publishing
enabled = 0

; IP addess or FQDN from MQTT server
broker_address = 192.168.2.169

; Port of the MQTT server
; default plaintext: 1883
; default TLS port: 8883
broker_port = 1883

; Time (seconds) between publishing data
; default: 5
; minimum value: 1
publish_interval = 5

; Enables TLS
;tls_enabled = 1

; Absolute path to the Certificate Authority certificate file that is to be treated as trusted by this client
;tls_path_to_ca = /data/keys/mosquitto.crt

; Disables verification of the server hostname in the server certificate
;tls_insecure = 1

; Username used for connection
;username = myuser

; Password used for connection
;password = mypassword

; Topic where the meters data as JSON string is published
topic_meters = enphase/envoy-s/meters

; Topic where the inverters data as JSON string is published
topic_inverters = enphase/envoy-s/inverters

; Topic where the devices data as JSON string is published
topic_devices = enphase/envoy-s/devices

; Topic where the events data as JSON string is published
topic_events = enphase/envoy-s/events
`

**Comment by mr-manuel** [comment]
1. Should download a file until you stop it.
4, The CPU of the Envoy is very slow and cannot process many requests.

All other look good to me.

If the powercycle and stopping the other scripts does not help you can try to update the firmware. I have the firmware `D5.0.62 (5e57a9) ` installed. Do you can update to the latest `D5.x.x` firmware with the Toolkit app without upgrading to `D7.x.x`?

**Comment by jeroenkl** [comment]
Trying to get support to update the gateway to 5.0.62 and not 7.x.x

**Comment by mr-manuel** [comment]
At the end of the page you can chat with them https://support.enphase.com/s/contact-us

**Comment by mr-manuel** [comment]
But the strange thing is, that you said that it worked for a short time. Have you removed the power from the Envoy for over a minute? Also let disabled all other scripts. The problem in this case is definitely on the Envoy-S which lets you fail the authentication.

**Comment by jeroenkl** [comment]
It didn't worked before, I was mentioning the MQTT data was seen with MQTT explorer when MQTT is enabled. But I'm not sure if this data was ok et all!  have still problems to get in working. I only can update to D7.x.x which I don't want.
Still investigating

**Comment by mr-manuel** [comment]
Ah ok. I understood that with MQTT you saw the right data.

> 1: Yes, but got a zero 0 als a return currently

In a file that you downloaded or displayed directly as webpage?

**Comment by jeroenkl** [comment]
It is just only the number zero on the webpage, no 'file download' started.
I checked with a different browser too.

Strange thing, my Home Assistant plugin is working and got all the info from the single inverters too.
In other words, I'm not sure if my envoy is the main problem

**Comment by mr-manuel** [comment]
Yes, the Envoy is the problem. The home assistant plugin probably is fetching the data from the JSON files `/production.json?details=1` and `/api/v1/production/inverters`, which caused more load on the Envoy in my test and was not as fast as getting the meters data from `/stream/meter`.

I check the firmware changelog, maybe I find something useful.

**Comment by jeroenkl** [comment]
Agree!
Thanks!

**Comment by mr-manuel** [comment]
> Trying to get support to update the gateway to 5.0.62 and not 7.x.x

I checked a few posts on the internet and a lot of people were able to update the Envoy to the latest D5.0.62 firmware using the Enphase Toolkit. Did you try that?

**Comment by jeroenkl** [comment]
> > Trying to get support to update the gateway to 5.0.62 and not 7.x.x
> 
> I checked a few posts on the internet and a lot of people were able to update the Envoy to the latest D5.0.62 firmware using the Enphase Toolkit. Did you try that?

I tried, but my app wants to update to 7.x.x. without choosing options.
Searching on internet for help

**Comment by moriss1919** [comment]
Hello

I have the same issue, any solution ?

**Comment by mr-manuel** [comment]
I need access to an Enphase Envoy with D7.x.x firmware and the Enphase account that is connected to, to solve this problem. You can contact me on Discord. The link is in my profile.

**Comment by mr-manuel** [comment]
I will release a version this week which supports the D5 and D7 firmware, so stay tuned :-)

**Comment by mr-manuel** [comment]
I released a new beta. Since it does work only for self installers currently I released it as beta version: https://github.com/mr-manuel/venus-os_dbus-enphase-envoy/releases/tag/v2.0.0-beta1
